### ISSUE TITLE
Double Menu entries

### ISSUE THREAD

**Issue by pellemans** [studer-raimann/CtrlMainMenu#19]
I upgraded an ILIAS site to 5.0 and also upgraded the CtrlMainMenu plugin. When activating the plugin I got an SQL error about PRIMARY key violation in table ctrl_classfile. I removed all entries from that table that had CtrlMainMenu in the plugin_path field. I was then able to activate CtrlMainMenu. 
However, all standard ILIAS menu entries had doubled up: Personal Desktop, Repository and Administration. I was able to remove the double entries for Personal Desktop and Repository using the plugin configuration. However, I am unable to remove the second Administration Menu; I only have an option to modify. By the way, the second Administration menu item does show any submenu items when I click it.
Any suggestions?
Thanks!
-Peter

**Comment by pellemans** [comment]
I removed all CtrlMainMenu related tables and removed the entry in ilPlugin and did a fresh install and configuration. Everything works fine now.

**Comment by wanze** [comment]
@pellemans Thanks for reporting this issue. The problems with the `ctrl_classfile` table appear if an old version of the plugin was installed before. Nice to hear that you already solved the problems, your solution is correct :) We will update the plugin so that old entries in `ctrl_classfile` are deleted properly.
I guess the duplicated entries are the result of executing some dbupdate steps twice.
